CREATE TABLE `game` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '游戏名',
	`version` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '版本',
	`type` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '类型',
	`language` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '语言',
	`size` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '大小',
	`update_date` DATE NOT NULL COMMENT '更新日期',
	`tags` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '标签',
	`brief` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '简介',
	`description` TEXT NOT NULL COMMENT '描述',
	`image` VARCHAR(80) NOT NULL DEFAULT '' COMMENT '图片',
	`screenshot` TEXT NOT NULL COMMENT '截屏',
	`add_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
	`status` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '状态',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
